language: node_js

node_js:
  - "10"

dist: trusty

sudo: required

services:
  - docker

script: "npm run test"

after_success:
  - npm run coverage

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./deploy-production.sh && npx semantic-release
